require("@rails/ujs").start()
// require("turbolinks").start()
require("@rails/activestorage").start()
require("channels")
require("../price")
require("../card")
require("../manyAttach")
require("../selectMainImage")

require("../items")